 1 Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.


In [4]:
import numpy as np


In [6]:
arr = np.arange(1, 11)
print(arr)
reshaped_arr = arr.reshape(2, 5)
print(reshaped_arr)


[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


 2 Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index.

In [14]:

arr = np.arange(1, 21)
arr
subset = arr[5:15]
print(subset)


[ 6  7  8  9 10 11 12 13 14 15]


 3 Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. Then, add a new item to the series with the key 'pears' and the value 4. 

In [24]:
import pandas as pd

In [26]:

fruit_series = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})
print(fruit_series)
fruit_series['pears'] = 4
print(fruit_series)


apples     3
bananas    2
oranges    1
dtype: int64
apples     3
bananas    2
oranges    1
pears      4
dtype: int64


4 Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data. 

In [28]:

data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Emma', 'Frank', 'Grace', 'Helen', 'Ian', 'Jack'],
    'age': [25, 30, 22, 28, 35, 40, 27, 26, 29, 31],
    'gender': ['Female', 'Male', 'Male', 'Male', 'Female', 'Male', 'Female', 'Female', 'Male', 'Male']
}

df = pd.DataFrame(data)
print(df)


      name  age  gender
0    Alice   25  Female
1      Bob   30    Male
2  Charlie   22    Male
3    David   28    Male
4     Emma   35  Female
5    Frank   40    Male
6    Grace   27  Female
7    Helen   26  Female
8      Ian   29    Male
9     Jack   31    Male


 5 Add a new column to the data frame created in question 1, called occupation. The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe. 

In [33]:

data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Emma', 'Frank', 'Grace', 'Helen', 'Ian', 'Jack'],
    'age': [25, 30, 22, 28, 35, 40, 27, 26, 29, 31],
    'gender': ['Female', 'Male', 'Male', 'Male', 'Female', 'Male', 'Female', 'Female', 'Male', 'Male']
}

df = pd.DataFrame(data)

occupations = ['Programmer', 'Manager', 'Analyst'] * (len(df) // 3) + ['Programmer']
df['occupation'] = occupations

print(df)


      name  age  gender  occupation
0    Alice   25  Female  Programmer
1      Bob   30    Male     Manager
2  Charlie   22    Male     Analyst
3    David   28    Male  Programmer
4     Emma   35  Female     Manager
5    Frank   40    Male     Analyst
6    Grace   27  Female  Programmer
7    Helen   26  Female     Manager
8      Ian   29    Male     Analyst
9     Jack   31    Male  Programmer


6 select the rows of the dataframe where the age is greater than or equal to 30.

In [35]:

data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Emma', 'Frank', 'Grace', 'Helen', 'Ian', 'Jack'],
    'age': [25, 30, 22, 28, 35, 40, 27, 26, 29, 31],
    'gender': ['Female', 'Male', 'Male', 'Male', 'Female', 'Male', 'Female', 'Female', 'Male', 'Male'],
    'occupation': ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
}

df = pd.DataFrame(data)
filtered_df = df[df['age'] >= 30]
print(filtered_df)


    name  age  gender  occupation
1    Bob   30    Male     Manager
4   Emma   35  Female     Manager
5  Frank   40    Male     Analyst
9   Jack   31    Male  Programmer


7 Convert this dataframe to a csv file and read that csv file, finally display the contents.

In [37]:

data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Emma', 'Frank', 'Grace', 'Helen', 'Ian', 'Jack'],
    'age': [25, 30, 22, 28, 35, 40, 27, 26, 29, 31],
    'gender': ['Female', 'Male', 'Male', 'Male', 'Female', 'Male', 'Female', 'Female', 'Male', 'Male'],
    'occupation': ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
}

df = pd.DataFrame(data)
csv_filename = "data.csv"
df.to_csv(csv_filename, index=False)
df1 = pd.read_csv(csv_filename)
print(df1)


      name  age  gender  occupation
0    Alice   25  Female  Programmer
1      Bob   30    Male     Manager
2  Charlie   22    Male     Analyst
3    David   28    Male  Programmer
4     Emma   35  Female     Manager
5    Frank   40    Male     Analyst
6    Grace   27  Female  Programmer
7    Helen   26  Female     Manager
8      Ian   29    Male     Analyst
9     Jack   31    Male  Programmer
